name: Pull and Run BusyBox on Windows Docker Desktop

on:
  workflow_dispatch:

jobs:
  run-busybox:
    runs-on: ubuntu-latest

    steps:
      - name: login to docker hub
        run: echo "${{ secrets.Cloudlearning@26 }}" | docker login -u "${{ secrets.261199 }}" --password-stdin
      
      - name: Pull BusyBox image
        run: docker pull busybox

      - name: Run BusyBox container
        run: docker run busybox echo "Hello from BusyBox on Windows!"
