name: MongoDB with Docker and Import JSON

on:
  push:
    paths:
      - 'file.json'
      - '.github/workflows/mongo-docker.yml'

jobs:
  mongo-docker-import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Start MongoDB Container
      run: |
        docker run -d --name mongodb -p 27017:27017 mongo:latest
        sleep 10  # give MongoDB time to start

    - name: Copy JSON File into Container
      run: docker cp file.json mongodb:/file.json

    - name: Import Data into MongoDB
      run: |
        docker exec mongodb mongoimport --db mydb --collection users --file /file.json --jsonArray

    - name: Verify Import
      run: |
        docker exec mongodb mongo mydb --eval "db.users.find().pretty()"

    - name: Stop and Remove Container
      run: docker rm -f mongodb
